- name: Configurando o hostname
  ansible.builtin.hostname:
    name: "{{ item }}"
  with_items: "{{ inventory_hostname }}"

- name: Instalando os pacotes basicos
  update_cache: yes
  apt:
    pkg:
      - ntp
      - htop
      - vim
      - apt-transport-https
      - ca-certificates
      - curl
      - net-tools
      - bash-completion

- name: Criando o usuário principal
  user:
    name: jeferson
    comment: jeferson
    uid: 1313
    shell: /bin/bash
    group: sudo
    append: yes

- name: Configurando o timezone
  shell: timedatectl set-timezone Europe/Amsterdam

- name: Reiniciando o serviço do NTP
  shell: service ntp restart

- name: Aguarda o APT sair do lock
  shell: while sudo fuser /var/lib/apt/lock >/dev/null 2>&1; do sleep 5; done;

- name: Atualizando todos os pacotes do SO
  apt:
    upgrade: dist
